"#include <iostream>" 
"using namespace std;" 
"" 
"class Product {" 
"public:" 
"    string name;" 
"    double price;" 
"};" 
"" 
"int main() {" 
"    Product p;" 
"    p.name = \"Телефон\";" 
"    p.price = 15000;" 
"    cout << p.name << \" - \" << p.price << \" руб.\" << endl;" 
"    return 0;" 
"}" 
