"#include <iostream>" 
"#include <string>" 
"" 
"class Product {" 
"public:" 
"    std::string name;" 
"    double price;" 
"};" 
"" 
"int main() {" 
"    Product laptop;" 
"    laptop.name = \"Ноутбук\";" 
"    laptop.price = 50000;" 
"    std::cout << laptop.name << \" - \" << laptop.price << \" руб.\" << std::endl;" 
"    return 0;" 
"}" 
